### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by fm1randa** [fm1randa/yagami#1]
### Subtasks
- [x] Give an overview of the entire project
- [x] Explain how to create commands
- [x] Explain how to create actions
- [x] Explain what is done in the database layer
