### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by fm1randa** [fm1randa/yagami#6]
Almost all text is written in Brazilian Portuguese. The objective is to have many languages for Yagami, and give the user the ability to choose a language.

### Subtasks
- [x] Translate all text to english
- [ ] Add a translation dependency
- [ ] Add other languages
